### PR TITLE
CRAB-37569: update the condition compatibility

### PR DESCRIPTION
**Pull request by bolorundurowb-sq**
Reviewer: @mar1u50 (via cpr)

- Add in unit tests
- Update the Newtonsoft Json dependency
- Update Seeq Link SDK to R61
- Improve Tag Value retrieval

### CODE REVIEW

**Comment by mar1u50** [comment]
Exploratory testing notes:
Run environemnt then build

🛑 Got 9 errors

```
DatasourceSimulator.cs(124,24): error CS1056: Unexpected character '$' [C:\Users\MariusO\Seeq12\Repos\seeq-connector-sdk-csharp\MyCompany.Seeq.Link.Connector.MyConnector\MyCompany.Seeq.Link.Connector.MyConnector.csproj]
DatasourceSimulator.cs(137,22): error CS1056: Unexpected character '$' [C:\Users\MariusO\Seeq12\Repos\seeq-connector-sdk-csharp\MyCompany.Seeq.Link.Connector.MyConnector\MyCompany.Seeq.Link.Connector.MyConnector.csproj]
DatasourceSimulator.cs(138,24): error CS1056: Unexpected character '$' [C:\Users\MariusO\Seeq12\Repos\seeq-connector-sdk-csharp\MyCompany.Seeq.Link.Connector.MyConnector\MyCompany.Seeq.Link.Connector.MyConnector.csproj]
"C:\Users\MariusO\Seeq12\Repos\seeq-connector-sdk-csharp\Seeq.Connector.SDK.sln" (default target) (1) ->
"C:\Users\MariusO\Seeq12\Repos\seeq-connector-sdk-csharp\MyCompany.Seeq.Link.Connector.MyConnector\MyCompany.Seeq.Link.Connector.MyConnector.csproj" (default target) (3) ->
(CoreCompile target) ->
  DatasourceSimulator.cs(124,24): error CS1056: Unexpected character '$' [C:\Users\MariusO\Seeq12\Repos\seeq-connector-sdk-csharp\MyCompany.Seeq.Link.Connector.MyConnector\MyCompany.Seeq.Link.Connector.MyConnector.csproj]
  DatasourceSimulator.cs(137,22): error CS1056: Unexpected character '$' [C:\Users\MariusO\Seeq12\Repos\seeq-connector-sdk-csharp\MyCompany.Seeq.Link.Connector.MyConnector\MyCompany.Seeq.Link.Connector.MyConnector.csproj]
  DatasourceSimulator.cs(138,24): error CS1056: Unexpected character '$' [C:\Users\MariusO\Seeq12\Repos\seeq-connector-sdk-csharp\MyCompany.Seeq.Link.Connector.MyConnector\MyCompany.Seeq.Link.Connector.MyConnector.csproj]
  DatasourceSimulator.cs(167,22): error CS1056: Unexpected character '$' [C:\Users\MariusO\Seeq12\Repos\seeq-connector-sdk-csharp\MyCompany.Seeq.Link.Connector.MyConnector\MyCompany.Seeq.Link.Connector.MyConnector.csproj]
  DatasourceSimulator.cs(168,29): error CS1056: Unexpected character '$' [C:\Users\MariusO\Seeq12\Repos\seeq-connector-sdk-csharp\MyCompany.Seeq.Link.Connector.MyConnector\MyCompany.Seeq.Link.Connector.MyConnector.csproj]
  DatasourceSimulator.cs(197,27): error CS1056: Unexpected character '$' [C:\Users\MariusO\Seeq12\Repos\seeq-connector-sdk-csharp\MyCompany.Seeq.Link.Connector.MyConnector\MyCompany.Seeq.Link.Connector.MyConnector.csproj]
  DatasourceSimulator.cs(198,29): error CS1056: Unexpected character '$' [C:\Users\MariusO\Seeq12\Repos\seeq-connector-sdk-csharp\MyCompany.Seeq.Link.Connector.MyConnector\MyCompany.Seeq.Link.Connector.MyConnector.csproj]
  DatasourceSimulator.cs(12,45): error CS1002: ; expected [C:\Users\MariusO\Seeq12\Repos\seeq-connector-sdk-csharp\MyCompany.Seeq.Link.Connector.MyConnector\MyCompany.Seeq.Link.Connector.MyConnector.csproj]
  DatasourceSimulator.cs(12,53): error CS1519: Invalid token ';' in class, struct, or interface member declaration [C:\Users\MariusO\Seeq12\Repos\seeq-connector-sdk-csharp\MyCompany.Seeq.Link.Connector.MyConnector\MyCompany.Seeq.Link.Connector.MyConnector.csproj]

    0 Warning(s)
    9 Error(s)

```

**Comment by mar1u50** [comment]
Exploratory testing notes:
command line build worked ✅ 
clean worked ✅ 
ide started the ide as expected ✅ 
Build > Build Solution worked ✅ 

I fill in the SeeqUrl in EntryPoint.cs
I enter the agent api key in data/keys/agent.key

I start EntryPoint

🛑 I got an error that websocket cannot connect.

The problem is that we only set 
```
            config.SeeqUrl = new Uri("https://r61.seeq.dev");
```
but the other two URls are not set (remaining at localhost).

I changed the Entrypoint to 
```
            config.SeeqUrl = new Uri("https://r61.seeq.dev");
            config.SeeqExternalUrl = new Uri("https://r61.seeq.dev");
            config.SeeqWebSocketUrl = new Uri("https://r61.seeq.dev");
```

Seeq started ✅ 
It indexed ✅ 
25 signals
19 conditions
32 scalars
5 assets

🛑 Found that readme.md contains a spelling error "my replacing". I think we can quicky fix this right here.

Assets, scalars and signals looks good ✅ 

🛑 I trended a few conditions and I don't seem to see anything on the trend (no capsules)

**Comment by mar1u50** [comment]
Exploratory testing notes:
Run `test` from command line and I can see 1 test executed ✅ 

I retested signals, assets, scalars, conditions and all worked now ✅ 
image


What it was a bit unexpected for me (but I'm ok to merging this way if it is only me) is that on every index we generate a different number of assets, signals, etc. IMHO these numbers should be in the configuration, not random because one can create a workbook and the signals won't be valid anymore after a re-index.

Also, It is a bit strange that the conditions are all zero length. I expected to see something more natural (some longer, some shorted, some zero length) but again it is not a merge blocker.

**Review by cherrera2001 — APPROVED** [review]
Exploratory testing notes:
✅ Agent connected
✅ Asset tree created
✅ Trended scalars, signals, and conditions

Looks great!

**Pull request merged**
